---
name: Build GO & Docker push
    
on:
  workflow_dispatch:
  push:
    tags: 'v*'

env:
  REGISTRY: docker.io
  IMAGE_NAME: loic79/cowsay-go

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          /amd64
          /arm64
          main.go
          go.sum

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build the cowsay amd64
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.4'
        check-latest: true
    - run: env GOOS=linux GOARCH=amd64 go build -o bin/amd64/cowsay main.go

    - name: Build the cowsay arm64
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.4'
        check-latest: true
    - run: env GOOS=linux GOARCH=arm64 go build -o bin/arm64/cowsay main.go

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME_LOIC }}
        password: ${{ secrets.DOCKERHUB_TOKEN_LOIC }}

    - name: Build and push amd64
      uses: docker/build-push-action@v6
      with:
        context: ./amd64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push arm64
      uses: docker/build-push-action@v6
      with:
        context: ./arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

